
UPDATE global_variables SET variable_value = 'clickhouse' WHERE variable_name = 'clickhouse-hostname';

LOAD CLICKHOUSE USERS TO RUNTIME;
LOAD CLICKHOUSE USERS TO MEMORY;
SAVE CLICKHOUSE USERS TO DISK;
LOAD MYSQL USERS TO RUNTIME;
SAVE MYSQL USERS TO DISK;
SAVE MYSQL SERVERS TO DISK;
LOAD MYSQL SERVERS TO RUNTIME;
LOAD MYSQL VARIABLES TO RUNTIME;
LOAD ADMIN VARIABLES TO RUNTIME;
LOAD CLICKHOUSE VARIABLES TO RUNTIME;
LOAD CLICKHOUSE USERS TO RUNTIME;
LOAD CLICKHOUSE USERS TO MEMORY;
SAVE CLICKHOUSE USERS TO DISK;
LOAD MYSQL USERS TO RUNTIME;
SAVE MYSQL USERS TO DISK;
SAVE MYSQL SERVERS TO DISK;
LOAD MYSQL SERVERS TO RUNTIME;
LOAD MYSQL VARIABLES TO RUNTIME;
LOAD ADMIN VARIABLES TO RUNTIME;
LOAD CLICKHOUSE VARIABLES TO RUNTIME;

